### ISSUE TITLE
Slack opens in browser

### ISSUE THREAD

**Issue by paoloantinori** [LibreRambox/LibreRambox#5]
### Steps to reproduce

1. connect to a private Slack
2. click on Workspace
3. 

### Expected behavior

to load the chat inside LibreRambox

### Actual behavior

shows a Workspaces selector, but after clicking on one of them, it opens them in the browser

### ENVIRONMENT

> Rambox: v0.8.1

> OS: Linx

> Arch: x64

**Comment by wolfposd** [comment]
works for me, need more information on this.

**Comment by mdouchement** [comment]
For months I received a message from Slack informing me that it would no longer support my browser (Electron) in September/October.
I think it's related to https://slack.com/help/articles/1500001836081-Slack-support-lifecycle-for-operating-systems-app-versions-and-browsers#browser-support-lifecycle

Now I have the following message and nothing happens when I click on the link:
> Click "Open Slack" to launch the desktop app.
> Not working? You can also [use Slack in your browser]().

I wonder if we can workaround this issue by spoofing the user agent.

NB: In the paste message, I removed the link's target.

**Comment by KevinRoebert** [comment]
@mdouchement The user agent for Slack is updated. The warning message should no longer appear.
